source 'https://rubygems.org'

gem 'rails', '3.2.9'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'execjs'
gem 'therubyracer'

# To use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

#Gema para autenticacion
gem 'devise'

#Gema para localidad
gem 'i18n'

#Gema para dataTables
gem 'jquery-datatables-rails'

# Para los forms
gem 'formalize-rails'
gem 'formtastic'

# Para validar fechas en el modelo
gem 'date_validator'

#jquery ui
gem "jquery-ui-rails", "~> 4.0.2"

#claves foraneas (no funciona con sqlite3, pero puede ser util cuando lo montemos con postgre o mysql
gem 'foreigner'

#gema para listar paises
gem 'country-select'
gem 'carmen-rails', '~> 1.0.0'

#gema para subir archivos
gem "paperclip", "~> 3.0"

#gema para renderizar pdfs
gem 'wicked_pdf'

#gemas para manejar archivos de ruby en js
gem 'rabl'
gem 'gon'

#Gema para tareas asincronas con cron
gem 'whenever', :require => false

gem 'paper_trail'
